vulnerability_id: CVE-2018-1000808
notes:
- links:
  - https://github.com/pyca/pyopenssl/pull/723
  - https://snyk.io/vuln/SNYK-PYTHON-PYOPENSSL-72430
  text: 'Python Cryptographic Authority pyopenssl version Before 17.5.0 contains a CWE - 401 : Failure to Release Memory Before Removing Last Reference vulnerability in PKCS #12 Store that can result in Denial of service if memory runs low or is exhausted. This attack appear to be exploitable via Depends upon calling application, however it could be as simple as initiating a TLS connection. Anything that would cause the calling application to reload certificates from a PKCS #12 store.. This vulnerability appears to have been fixed in 17.5.0.'
fixes:
- id: DEFAULT_BRANCH
  commits:
  - id: e73818600065821d588af475b024f4eb518c3509
    repository: https://github.com/pyca/pyopenssl
artifacts:
- id: pkg:maven/pyOpenSSL/pyOpenSSL@18.0.0
  reason: Assessed with Eclipse Steady (AST_EQUALITY)
  affected: false
- id: pkg:maven/pyOpenSSL/pyOpenSSL@18.0.0
  reason: Reviewed manually
  affected: false
- id: pkg:maven/pyOpenSSL/pyOpenSSL@19.0.0
  reason: Assessed with Eclipse Steady (AST_EQUALITY)
  affected: false
- id: pkg:maven/pyOpenSSL/pyOpenSSL@19.1.0
  reason: Assessed with Eclipse Steady (AST_EQUALITY)
  affected: false
- id: pkg:maven/pyOpenSSL/pyOpenSSL@16.0.0
  reason: Assessed with Eclipse Steady (AST_EQUALITY)
  affected: true
- id: pkg:maven/pyOpenSSL/pyOpenSSL@17.5.0
  reason: Assessed with Eclipse Steady (AST_EQUALITY)
  affected: false
- id: pkg:maven/pyOpenSSL/pyOpenSSL@17.5.0
  reason: Reviewed manually
  affected: false
- id: pkg:maven/pyOpenSSL/pyOpenSSL@0.15.1
  reason: Assessed with Eclipse Steady (AST_EQUALITY)
  affected: true
