vulnerability_id: CVE-2018-1000807
notes:
- links:
  - https://github.com/pyca/pyopenssl/pull/723
  - https://snyk.io/vuln/SNYK-PYTHON-PYOPENSSL-72429
  text: 'Python Cryptographic Authority pyopenssl version prior to version 17.5.0 contains a CWE-416: Use After Free vulnerability in X509 object handling that can result in Use after free can lead to possible denial of service or remote code execution.. This attack appear to be exploitable via Depends on the calling application and if it retains a reference to the memory.. This vulnerability appears to have been fixed in 17.5.0.'
fixes:
- id: DEFAULT_BRANCH
  commits:
  - id: e73818600065821d588af475b024f4eb518c3509
    repository: https://github.com/pyca/pyopenssl
artifacts:
- id: pkg:maven/pyOpenSSL/pyOpenSSL@18.0.0
  reason: Reviewed manually
  affected: false
- id: pkg:maven/pyOpenSSL/pyOpenSSL@16.0.0
  reason: Assessed with Eclipse Steady (AST_EQUALITY)
  affected: true
- id: pkg:maven/pyOpenSSL/pyOpenSSL@16.0.0
  reason: Reviewed manually
  affected: true
- id: pkg:maven/pyOpenSSL/pyOpenSSL@18.0.0
  reason: Assessed with Eclipse Steady (AST_EQUALITY)
  affected: false
- id: pkg:maven/pyOpenSSL/pyOpenSSL@17.5.0
  reason: Assessed with Eclipse Steady (AST_EQUALITY)
  affected: false
- id: pkg:maven/pyOpenSSL/pyOpenSSL@0.15.1
  reason: Assessed with Eclipse Steady (AST_EQUALITY)
  affected: true
- id: pkg:maven/pyOpenSSL/pyOpenSSL@17.5.0
  reason: Reviewed manually
  affected: false
- id: pkg:maven/pyOpenSSL/pyOpenSSL@19.0.0
  reason: Assessed with Eclipse Steady (AST_EQUALITY)
  affected: false
- id: pkg:maven/pyOpenSSL/pyOpenSSL@19.1.0
  reason: Assessed with Eclipse Steady (AST_EQUALITY)
  affected: false
